name: Continuous Integration
on:
  pull_request:
    branches: [ master ]

jobs:
  check-awk:
    name: Check .awk files
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Lint .awk files
        run: |
          declare -ir ERRORS_FOUND=1

          output="$(awk --lint=no-ext -f parseopts.awk 2>&1)"
          echo "$output"

          if [[ -n $output ]]; then
            exit $ERRORS_FOUND
          fi
  
  check-markdown:
    name: Check .md files
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Lint .md files
        run: |
          npm install -g markdownlint-cli
          markdownlint *.md
