name: Continuous Integration
on:
  pull_request:
    branches: [ master ]

jobs:
  check-awk:
    name: Check .awk files
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Lint .awk files
        run: |
          awk --lint=no-ext -f parseopts.awk
